# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def load_data(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    User(
        password="pbkdf2_sha256$30000$0BfJVrfm5AvE$iwol86B/iFilHue6idT/uJFa2q0A8qSNdN0GVkx0w9E=",
        last_login="2016-08-30T11:14:12.239Z",
        is_superuser=True,
        username="admin",
        first_name="",
        last_name="",
        email="admin@example.com",
        is_staff=True,
        is_active=True,
        date_joined="2016-08-30T11:13:27.530Z",
    ).save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
      ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]


